language: objective-c
osx_image: xcode7.2

script:
  xctool
  -workspace ZZOperationExtension.xworkspace
  -scheme ZZOperationExtension
  -sdk iphonesimulator
  build
  test
  ONLY_VALID_ARCH=NO
  CODE_SIGNING_REQUIRED=NO

before_install:
  - brew update
  - brew install xctool
