language: objective-c
osx_image: xcode7.2

xcode_project: ZZOperationExtension.xcodeproj
xcode_scheme: ZZOperationExtension

script:
  xctool
  -sdk iphonesimulator
  build
  test
  ONLY_VALID_ARCH=NO
  CODE_SIGNING_REQUIRED=NO

before_install:
  - brew update
  - brew install xctool
