language: objective-c
osx_image: xcode7.2

script:
  -pod spec lint ZZOperationExtension.podspec
  -xctool -project ZZOperationExtension.xcodeproj -scheme ZZOperationExtension -sdk iphonesimulator build test ONLY_VALID_ARCH=NO CODE_SIGNING_REQUIRED=NO

before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
